#!/usr/bin/env python3
"""Build a local DuckDB database from the kb/publications/ YAML knowledge base.

The YAML files are the source of truth; this database is a generated product,
rebuilt by `just build-db` and never hand-edited.

Layers
------
L1  One table per concrete LinkML class, with value objects flattened into
    named columns (see scripts/soma_duckdb.py for the mapping rules), plus
    three tables the schema does not itself declare:

      measurement  long-format: one row per number anywhere in the KB, with
                   its unit, dispersion, central tendency and sample size.
                   The wide tables carry a compact 3-column echo of the same
                   value for ergonomic wide queries; this table is canonical.
      link         every entity-to-entity edge (parent_type, parent_id,
                   parent_slot, target_type, target_id). Authoritative for
                   many-to-many relationships such as follows_protocols.
      term         every ontology term the KB references, with its label.

L2  Views that make the layered model queryable without knowing the schema:
    assay, assay_output, measurement_full, evidence, term_usage.

Usage:
    uv run python scripts/build_duckdb.py                       # kb/ (or tests/data/valid if empty)
    uv run python scripts/build_duckdb.py --kb-dir tests/data/valid
    uv run python scripts/build_duckdb.py --ddl-only            # print DDL, build nothing
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from soma_duckdb import (  # noqa: E402
    PAPER_TABLE,
    PARENT_COLUMNS,
    PROVENANCE_COLUMNS,
    QUANTITY_CLASSES,
    ROOT_CLASS,
    TERM_CLASSES,
    columns_for,
    concrete_class,
    has_natural_key,
    is_entity,
    load_schema,
    table_classes,
)

DEFAULT_KB_DIR = ROOT / "kb" / "publications"
FALLBACK_KB_DIR = ROOT / "tests" / "data" / "valid"
DEFAULT_OUT = ROOT / "exports" / "soma.duckdb"


# ---------------------------------------------------------------------------
# DDL
# ---------------------------------------------------------------------------

MEASUREMENT_DDL = """
CREATE TABLE measurement (
    paper_id      VARCHAR,
    source_file   VARCHAR,
    entity_type   VARCHAR,
    entity_id     VARCHAR,
    entity_name   VARCHAR,
    slot_name     VARCHAR,
    value         VARCHAR,
    value_num     DOUBLE,
    min_value     VARCHAR,
    max_value     VARCHAR,
    unit          VARCHAR,
    unit_label    VARCHAR,
    central_tendency   VARCHAR,
    sample_size        BIGINT,
    variability_type   VARCHAR,
    variability_value  VARCHAR,
    lower_bound        VARCHAR,
    upper_bound        VARCHAR
);
CREATE TABLE link (
    paper_id     VARCHAR,
    source_file  VARCHAR,
    parent_type  VARCHAR,
    parent_id    VARCHAR,
    parent_slot  VARCHAR,
    target_type  VARCHAR,
    target_id    VARCHAR,
    inlined      BOOLEAN
);
CREATE TABLE term (
    id          VARCHAR PRIMARY KEY,
    label       VARCHAR,
    prefix      VARCHAR
);
CREATE TABLE paper (
    paper_id        VARCHAR PRIMARY KEY,
    source_file     VARCHAR,
    reference       VARCHAR,
    reference_title VARCHAR,
    doi             VARCHAR
);
"""


def emit_ddl(sv) -> str:
    """Generate the L1 DDL from the schema."""
    parts = [
        "-- Generated by scripts/build_duckdb.py from the soma-schema LinkML schema.",
        "-- Do not edit: regenerate with `just db-schema`.",
        MEASUREMENT_DDL.strip(),
        "",
    ]
    for cls in table_classes(sv):
        cols = list(PROVENANCE_COLUMNS) + list(PARENT_COLUMNS) + columns_for(sv, cls)
        seen, deduped = set(), []
        for name, typ in cols:
            if name in seen:
                continue
            seen.add(name)
            deduped.append((name, typ))
        lines = [f'    "{n}" {t}' for n, t in deduped]
        if has_natural_key(sv, cls):
            lines.append('    PRIMARY KEY ("paper_id", "id")')
        body = ",\n".join(lines)
        parts.append(f'CREATE TABLE "{cls}" (\n{body}\n);')
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Walker
# ---------------------------------------------------------------------------

class Builder:
    def __init__(self, sv):
        self.sv = sv
        self.rows: dict[str, dict[tuple, dict]] = defaultdict(dict)
        self.measurements: list[dict] = []
        self.links: list[dict] = []
        self.terms: dict[str, tuple[str, str]] = {}
        self.papers: list[dict] = []
        self.surrogate: dict[str, int] = defaultdict(int)
        self.warnings: list[str] = []

    # -- helpers ----------------------------------------------------------
    def _term(self, obj):
        """Record an ontology term reference; return (curie, label)."""
        if obj is None:
            return None, None
        if isinstance(obj, str):
            return obj, None
        curie, label = obj.get("id"), obj.get("name")
        if curie:
            prefix = curie.split(":")[0] if ":" in curie else ""
            existing = self.terms.get(curie)
            if existing is None or (not existing[0] and label):
                self.terms[curie] = (label, prefix)
        return curie, label

    def _quantity(self, obj, entity_type, entity_id, entity_name, slot, ctx, rng):
        """Flatten a value object and append its long-format measurement row."""
        if not isinstance(obj, dict):
            return {}
        unit, unit_label = self._term(obj.get("unit"))
        if rng == "QuantityRange":
            mn, mx = obj.get("min_value"), obj.get("max_value")
            if isinstance(mn, dict):
                mn = mn.get("value")
            if isinstance(mx, dict):
                mx = mx.get("value")
            flat = {
                f"{slot}_min_value": _s(mn),
                f"{slot}_max_value": _s(mx),
                f"{slot}_unit": unit,
                f"{slot}_unit_label": unit_label,
            }
            self.measurements.append({
                **ctx, "entity_type": entity_type, "entity_id": entity_id,
                "entity_name": entity_name, "slot_name": slot,
                "value": None, "value_num": None,
                "min_value": _s(mn), "max_value": _s(mx),
                "unit": unit, "unit_label": unit_label,
                "central_tendency": None, "sample_size": None,
                "variability_type": None, "variability_value": None,
                "lower_bound": None, "upper_bound": None,
            })
            return flat

        value = _s(obj.get("value"))
        var = obj.get("variability") or {}
        if not isinstance(var, dict):
            var = {}
        flat = {
            f"{slot}_value": value,
            f"{slot}_unit": unit,
            f"{slot}_unit_label": unit_label,
        }
        self.measurements.append({
            **ctx, "entity_type": entity_type, "entity_id": entity_id,
            "entity_name": entity_name, "slot_name": slot,
            "value": value, "value_num": _num(value),
            "min_value": None, "max_value": None,
            "unit": unit, "unit_label": unit_label,
            "central_tendency": _s(obj.get("central_tendency")),
            "sample_size": obj.get("sample_size"),
            "variability_type": _s(var.get("variability_type")),
            "variability_value": _s(var.get("value")),
            "lower_bound": _s(var.get("lower_bound")),
            "upper_bound": _s(var.get("upper_bound")),
        })
        return flat

    # -- main recursion ---------------------------------------------------
    def visit(self, obj, declared, ctx, parent=None):
        """Emit a row for `obj` and recurse into its inlined children.

        Returns the row's id so the caller can store a foreign key.
        """
        sv = self.sv
        cls = concrete_class(sv, declared, obj)
        if cls not in self.rows and cls not in table_classes(sv):
            return None

        natural = has_natural_key(sv, cls)
        if natural:
            row_id = obj.get("id")
            if row_id is None:
                self.warnings.append(f"{ctx['source_file']}: {cls} with no id, skipped")
                return None
        else:
            self.surrogate[cls] += 1
            row_id = self.surrogate[cls]

        key = (ctx["paper_id"], row_id)
        row = self.rows[cls].get(key)
        first_time = row is None
        if first_time:
            row = {**ctx, "id": row_id}
            if parent:
                row["parent_type"], row["parent_id"], row["parent_slot"] = parent
            self.rows[cls][key] = row
        elif parent and row.get("parent_id") not in (None, parent[1]):
            # A shared child (a protocol reused by two assays). The row is kept
            # once; `link` carries every edge. parent_* reflects the first
            # parent seen, so the edge table is what queries should use.
            pass

        name = obj.get("name")
        for s in sv.class_induced_slots(cls):
            val = obj.get(s.name)
            if val is None:
                continue
            rng = s.range
            if s.designates_type:
                row[s.name] = _s(val)
            elif is_entity(sv, rng):
                self._entity_slot(row, s, val, rng, cls, row_id, ctx)
            elif rng in QUANTITY_CLASSES:
                row.update(self._quantity(val, cls, row_id, name, s.name, ctx, rng))
            elif rng in TERM_CLASSES:
                if s.multivalued:
                    pairs = [self._term(v) for v in val or []]
                    row[s.name] = [p[0] for p in pairs]
                    row[f"{s.name}_labels"] = [p[1] for p in pairs]
                else:
                    curie, label = self._term(val)
                    row[s.name] = curie
                    row[f"{s.name}_label"] = label
            else:
                if s.multivalued:
                    row[s.name] = [_s(v) for v in (val if isinstance(val, list) else [val])]
                else:
                    row[s.name] = val if not isinstance(val, (dict, list)) else _s(val)
        return row_id

    def _entity_slot(self, row, s, val, rng, cls, row_id, ctx):
        """Handle a slot whose range is a class that gets its own table."""
        items = val if s.multivalued else [val]
        for item in items or []:
            if isinstance(item, dict):
                child_declared = rng
                child_id = self.visit(
                    item, child_declared, ctx, parent=(cls, row_id, s.name)
                )
                child_type = concrete_class(self.sv, rng, item)
                inlined = True
            else:
                child_id, child_type, inlined = item, rng, False
            if child_id is None:
                continue
            self.links.append({
                **ctx, "parent_type": cls, "parent_id": _s(row_id),
                "parent_slot": s.name, "target_type": child_type,
                "target_id": _s(child_id), "inlined": inlined,
            })
            if not s.multivalued:
                row[f"{s.name}_id"] = _s(child_id)

    # -- file entry point -------------------------------------------------
    def add_file(self, path: Path):
        data = yaml.safe_load(path.read_text()) or {}
        src = data.get("source_publication") or {}
        paper_id = src.get("reference") or path.name
        ctx = {"paper_id": paper_id, "source_file": path.name}
        self.papers.append({
            "paper_id": paper_id,
            "source_file": path.name,
            "reference": src.get("reference"),
            "reference_title": src.get("reference_title"),
            "doi": src.get("doi"),
        })
        for s in self.sv.class_induced_slots(ROOT_CLASS):
            val = data.get(s.name)
            if val is None or not is_entity(self.sv, s.range):
                continue
            for item in (val if s.multivalued else [val]):
                if isinstance(item, dict):
                    self.visit(item, s.range, ctx, parent=(PAPER_TABLE, paper_id, s.name))


def _s(v):
    return None if v is None else str(v)


def _num(v):
    try:
        return float(str(v).strip().lstrip("<>~≈").replace(",", ""))
    except (TypeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# L2 views
# ---------------------------------------------------------------------------

def emit_views(sv) -> str:
    """Generate the analysis views.

    These exist so a question like "every ciliary beat frequency measured under
    PM2.5" does not require knowing that assays are split across 11 tables and
    outputs across 11 more.
    """
    assays = _subclasses(sv, "Assay")
    outputs = _subclasses(sv, "AssayOutputMeasurement")
    parts = []

    parts.append(_union_view(sv, "assay", "Assay", assays, "assay_type"))
    parts.append(
        _union_view(
            sv, "assay_output", "AssayOutputMeasurement", outputs, "output_type",
            extra=[("assay_id", '"parent_id"')],
        )
    )

    parts.append("""
-- Every number in the KB with its full experimental context: which paper,
-- which assay, which exposure, which experimental group, which key event.
-- This is the flagship table for analysis and the headline TSV export.
CREATE VIEW measurement_full AS
SELECT
    m.paper_id,
    p.reference_title,
    a.assay_type,
    a.id            AS assay_id,
    a.name          AS assay_name,
    o.output_type,
    m.entity_id     AS output_id,
    m.entity_name   AS output_name,
    o.experimental_group,
    m.slot_name     AS measurement,
    m.value,
    m.value_num,
    m.unit,
    m.unit_label,
    m.central_tendency,
    m.sample_size,
    m.variability_type,
    m.variability_value,
    m.lower_bound,
    m.upper_bound,
    e.id                                AS exposure_id,
    e.exposure_agent                    AS exposure_agent,
    e.exposure_agent_label              AS exposure_agent_label,
    e.exposure_concentration_value      AS exposure_concentration,
    e.exposure_concentration_unit_label AS exposure_concentration_unit,
    e.exposure_duration_value           AS exposure_duration,
    e.exposure_duration_unit_label      AS exposure_duration_unit,
    a.informs_on_key_event_id           AS key_event_id,
    ke.name                             AS key_event_name,
    m.source_file
FROM measurement m
LEFT JOIN assay_output o
       ON o.paper_id = m.paper_id AND o.id = m.entity_id
LEFT JOIN assay a
       ON a.paper_id = o.paper_id AND a.id = o.assay_id
LEFT JOIN "ExposureCondition" e
       ON e.paper_id = o.paper_id AND e.id = o.measured_under_id
LEFT JOIN "KeyEvent" ke
       ON ke.paper_id = a.paper_id AND ke.id = a.informs_on_key_event_id
LEFT JOIN paper p
       ON p.paper_id = m.paper_id;
""".strip())

    parts.append("""
-- Evidence quotes with the entity they support, resolved to one parent column.
CREATE VIEW evidence AS
SELECT
    ev.paper_id,
    ev.parent_type,
    ev.parent_id,
    ev.parent_slot,
    ev.supports,
    ev.evidence_source,
    ev.reference,
    ev.reference_title,
    ev.snippet,
    ev.explanation,
    ev.source_file
FROM "EvidenceItem" ev;
""".strip())

    parts.append("""
-- Which ontology terms the KB actually uses, and how often.
CREATE VIEW term_usage AS
SELECT t.id, t.label, t.prefix, u.n_uses, u.n_papers
FROM term t
LEFT JOIN (
    SELECT unit AS id, COUNT(*) AS n_uses, COUNT(DISTINCT paper_id) AS n_papers
    FROM measurement WHERE unit IS NOT NULL GROUP BY unit
) u ON u.id = t.id;
""".strip())

    return "\n\n".join(parts) + "\n"


def _subclasses(sv, parent: str) -> list[str]:
    """Concrete descendants of an abstract parent class, in schema order."""
    return [
        c for c in table_classes(sv)
        if parent in sv.class_ancestors(c) and c != parent
    ]


def _union_view(sv, view, parent, classes, type_col, extra=None):
    """UNION ALL the subclass tables over the columns they all inherit."""
    base = [n for n, _ in columns_for(sv, parent)]
    cols = ["paper_id", "source_file", "parent_id"] + base
    selects = []
    for cls in classes:
        available = {n for n, _ in columns_for(sv, cls)} | {
            "paper_id", "source_file", "parent_id", "parent_type", "parent_slot"
        }
        exprs = [f"'{cls}' AS {type_col}"]
        for c in cols:
            exprs.append(f'"{c}"' if c in available else f'NULL AS "{c}"')
        for alias, expr in (extra or []):
            exprs.append(f'{expr} AS "{alias}"')
        selects.append(f'SELECT {", ".join(exprs)} FROM "{cls}"')
    body = "\nUNION ALL\n".join(selects)
    return f"-- {view}: all {len(classes)} {parent} subclasses in one relation.\nCREATE VIEW {view} AS\n{body};"


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

def _execute_script(con, script: str):
    """Run a multi-statement script, skipping -- comment lines.

    The comment lines matter: LinkML-style DDL comments contain semicolons and
    prose, so they must be stripped before splitting rather than after.
    """
    clean = "\n".join(
        l for l in script.splitlines() if not l.lstrip().startswith("--")
    )
    for stmt in (s.strip() for s in clean.split(";")):
        if stmt:
            con.execute(stmt)


def _insert(con, table, rows):
    if not rows:
        return 0
    cols = [r[0] for r in con.execute(f'DESCRIBE "{table}"').fetchall()]
    placeholders = ", ".join("?" for _ in cols)
    payload = [tuple(r.get(c) for c in cols) for r in rows]
    con.executemany(
        f'INSERT INTO "{table}" ({", ".join(chr(34)+c+chr(34) for c in cols)}) '
        f"VALUES ({placeholders})",
        payload,
    )
    return len(payload)


def build(kb_dir: Path, out: Path, schema_path: str) -> dict:
    import duckdb

    sv = load_schema(schema_path)
    files = sorted(kb_dir.glob("*.yaml"))
    if not files:
        raise SystemExit(f"No YAML files in {kb_dir} — nothing to build.")

    b = Builder(sv)
    for f in files:
        b.add_file(f)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.unlink(missing_ok=True)
    con = duckdb.connect(str(out))
    _execute_script(con, emit_ddl(sv))

    counts = {}
    counts["paper"] = _insert(con, "paper", b.papers)
    for cls, rowmap in b.rows.items():
        n = _insert(con, cls, list(rowmap.values()))
        if n:
            counts[cls] = n
    counts["measurement"] = _insert(con, "measurement", b.measurements)
    counts["link"] = _insert(con, "link", b.links)
    counts["term"] = _insert(
        con, "term",
        [{"id": k, "label": v[0], "prefix": v[1]} for k, v in sorted(b.terms.items())],
    )
    _execute_script(con, emit_views(sv))
    con.close()
    return {"files": len(files), "counts": counts, "warnings": b.warnings}


# ---------------------------------------------------------------------------
# TSV export
# ---------------------------------------------------------------------------

def dump_tsv(db: Path, out_dir: Path) -> list[str]:
    """One .tsv per table and view.

    DuckDB's own `EXPORT DATABASE` is one command but lowercases filenames and
    writes tab-delimited data into files named `.csv`, which Excel mis-parses on
    double-click. Copying table by table keeps the class names and an honest
    extension. LIST columns are joined with '; ' so the output stays rectangular.
    """
    import duckdb

    con = duckdb.connect(str(db), read_only=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    rels = con.execute(
        "SELECT table_name, table_type FROM information_schema.tables "
        "WHERE table_schema = 'main' ORDER BY table_type, table_name"
    ).fetchall()
    for name, _type in rels:
        cols = con.execute(f'DESCRIBE "{name}"').fetchall()
        exprs = []
        for col, typ, *_ in cols:
            if typ.endswith("[]"):
                exprs.append(f'array_to_string("{col}", \'; \') AS "{col}"')
            else:
                exprs.append(f'"{col}"')
        target = out_dir / f"{name}.tsv"
        con.execute(
            f'COPY (SELECT {", ".join(exprs)} FROM "{name}") '
            f"TO '{target}' (FORMAT CSV, DELIMITER '\t', HEADER, QUOTE '\"')"
        )
        written.append(target.name)
    con.close()
    return written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def resolve_kb_dir(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit)
    if DEFAULT_KB_DIR.exists() and any(DEFAULT_KB_DIR.glob("*.yaml")):
        return DEFAULT_KB_DIR
    print(
        f"note: {DEFAULT_KB_DIR.relative_to(ROOT)} is empty, "
        f"building from {FALLBACK_KB_DIR.relative_to(ROOT)} instead",
        file=sys.stderr,
    )
    return FALLBACK_KB_DIR


def default_schema() -> str:
    from importlib.resources import files as pkg_files

    return str(pkg_files("soma") / "schema" / "soma.yaml")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--kb-dir")
    ap.add_argument("--output", default=str(DEFAULT_OUT))
    ap.add_argument("--schema", default=None)
    ap.add_argument("--tsv-dir", help="also dump every table/view as TSV here")
    ap.add_argument("--ddl-only", action="store_true", help="print DDL + views, build nothing")
    args = ap.parse_args(argv)

    schema_path = args.schema or default_schema()
    if args.ddl_only:
        sv = load_schema(schema_path)
        print(emit_ddl(sv))
        print(emit_views(sv))
        return 0

    kb_dir = resolve_kb_dir(args.kb_dir)
    out = Path(args.output)
    result = build(kb_dir, out, schema_path)

    print(f"Built {out} from {result['files']} files in {kb_dir}")
    nonempty = {k: v for k, v in sorted(result["counts"].items()) if v}
    print(f"{len(nonempty)} non-empty tables, {sum(nonempty.values())} rows")
    for k, v in sorted(nonempty.items(), key=lambda kv: -kv[1])[:12]:
        print(f"    {k:34} {v:6}")
    for w in result["warnings"][:10]:
        print(f"  WARNING: {w}", file=sys.stderr)

    if args.tsv_dir:
        written = dump_tsv(out, Path(args.tsv_dir))
        print(f"Wrote {len(written)} TSV files to {args.tsv_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
