#!/usr/bin/env python3
"""Build a local DuckDB database from the kb/publications/ YAML knowledge base.

The YAML files are the source of truth; this database is a generated product,
rebuilt by `just build-db` and never hand-edited.

Layers
------
L1  One table per concrete LinkML class, with value objects flattened into
    named columns (see scripts/soma_duckdb.py for the mapping rules), plus
    three tables the schema does not itself declare:

      measurement  long-format: one row per number anywhere in the KB, with
                   its unit, dispersion, central tendency and sample size.
                   The wide tables carry a compact 3-column echo of the same
                   value for ergonomic wide queries; this table is canonical.
      link         every entity-to-entity edge (parent_type, parent_id,
                   parent_slot, target_type, target_id). Authoritative for
                   many-to-many relationships such as follows_protocols.
      term         every ontology term the KB references, with its label.

L2  Views that make the layered model queryable without knowing the schema:
    assay, assay_output, measurement_full, evidence, term_usage.

Usage:
    uv run python scripts/build_duckdb.py                       # kb/ (or tests/data/valid if empty)
    uv run python scripts/build_duckdb.py --kb-dir tests/data/valid
    uv run python scripts/build_duckdb.py --ddl-only            # print DDL, build nothing
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from soma_duckdb import (  # noqa: E402
    PAPER_TABLE,
    PARENT_COLUMNS,
    PROVENANCE_COLUMNS,
    QUANTITY_CLASSES,
    ROOT_CLASS,
    TERM_CLASSES,
    columns_for,
    concrete_class,
    has_natural_key,
    is_entity,
    load_schema,
    table_classes,
)

DEFAULT_KB_DIR = ROOT / "kb" / "publications"
FALLBACK_KB_DIR = ROOT / "tests" / "data" / "valid"
DEFAULT_OUT = ROOT / "exports" / "soma.duckdb"


# ---------------------------------------------------------------------------
# DDL
# ---------------------------------------------------------------------------

MEASUREMENT_DDL = """
CREATE TABLE measurement (
    paper_id      VARCHAR,
    source_file   VARCHAR,
    entity_type   VARCHAR,
    entity_id     VARCHAR,
    entity_name   VARCHAR,
    slot_name     VARCHAR,
    value         VARCHAR,
    value_num     DOUBLE,
    value_qualifier VARCHAR,
    min_value     VARCHAR,
    max_value     VARCHAR,
    unit          VARCHAR,
    unit_label    VARCHAR,
    central_tendency   VARCHAR,
    sample_size        BIGINT,
    variability_type   VARCHAR,
    variability_value  VARCHAR,
    lower_bound        VARCHAR,
    upper_bound        VARCHAR
);
CREATE TABLE link (
    paper_id     VARCHAR,
    source_file  VARCHAR,
    parent_type  VARCHAR,
    parent_id    VARCHAR,
    parent_slot  VARCHAR,
    target_type  VARCHAR,
    target_id    VARCHAR,
    inlined      BOOLEAN
);
CREATE TABLE term (
    id          VARCHAR PRIMARY KEY,
    label       VARCHAR,
    prefix      VARCHAR
);
-- Every ontology term reference, so term_usage can count all of them rather
-- than only the ones that happened to be units.
CREATE TABLE term_ref (
    paper_id     VARCHAR,
    source_file  VARCHAR,
    entity_type  VARCHAR,
    entity_id    VARCHAR,
    slot_name    VARCHAR,
    term_id      VARCHAR
);
-- Keyed on source_file, not the cited PMID: two kb files may legitimately cite
-- one paper (a re-extraction, or a paper split across files), and keying on the
-- PMID would either abort the build on a primary-key clash or silently merge
-- the two files' entities into each other. paper_id stays as an attribute.
CREATE TABLE paper (
    source_file     VARCHAR PRIMARY KEY,
    paper_id        VARCHAR,
    reference       VARCHAR,
    reference_title VARCHAR,
    doi             VARCHAR
);
"""


def emit_ddl(sv) -> str:
    """Generate the L1 DDL from the schema."""
    parts = [
        "-- Generated by scripts/build_duckdb.py from the soma-schema LinkML schema.",
        "-- Do not edit: regenerate with `just db-schema`.",
        MEASUREMENT_DDL.strip(),
        "",
    ]
    for cls in sorted(table_classes(sv)):
        cols = list(PROVENANCE_COLUMNS) + list(PARENT_COLUMNS) + columns_for(sv, cls)
        seen, deduped = set(), []
        for name, typ in cols:
            if name in seen:
                continue
            seen.add(name)
            deduped.append((name, typ))
        lines = [f'    "{n}" {t}' for n, t in deduped]
        if has_natural_key(sv, cls):
            lines.append('    PRIMARY KEY ("source_file", "id")')
        body = ",\n".join(lines)
        parts.append(f'CREATE TABLE "{cls}" (\n{body}\n);')
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Walker
# ---------------------------------------------------------------------------

class Builder:
    def __init__(self, sv):
        self.sv = sv
        self.rows: dict[str, dict[tuple, dict]] = defaultdict(dict)
        # measurements and links are keyed, not appended: the same entity is
        # often inlined in full under several parents (one exposure condition
        # under six assays in the fixtures), and re-walking it must not emit
        # its numbers or its edges again.
        self.measurements: dict[tuple, dict] = {}
        self.links: dict[tuple, dict] = {}
        self.term_refs: set[tuple] = set()
        self.terms: dict[str, tuple[str, str]] = {}
        self.papers: list[dict] = []
        # One counter across all surrogate-keyed classes. Per-class counters
        # made PublicationReference '1' and EvidenceItem '1' collide, which the
        # cross-class id check and the link resolver both read as one row.
        self.surrogate = 0
        self.surrogate_ids: dict[tuple, int] = {}
        self.id_class: dict[tuple, str] = {}
        self.warnings: list[tuple[str, str]] = []

    def warn(self, category: str, message: str):
        """Record a warning under a category.

        Categorised rather than a flat list: a build with 30 content conflicts
        would otherwise truncate the one warning saying two files cite the same
        paper, which is the kind that changes what a curator does next.
        """
        self.warnings.append((category, message))

    # -- helpers ----------------------------------------------------------
    def _term(self, obj, ref=None):
        """Record an ontology term reference; return (curie, label).

        `ref` is (ctx, entity_type, entity_id, slot_name) when the caller knows
        where the reference sits, which feeds the term_ref table.
        """
        if obj is None:
            return None, None
        curie = obj if isinstance(obj, str) else obj.get("id")
        if curie and ref is not None:
            ctx, etype, eid, slot = ref
            self.term_refs.add(
                (ctx["paper_id"], ctx["source_file"], etype, _s(eid), slot, curie)
            )
        if isinstance(obj, str):
            return obj, None
        label = obj.get("name")
        if curie:
            prefix = curie.split(":")[0] if ":" in curie else ""
            existing = self.terms.get(curie)
            if existing is None or (not existing[0] and label):
                self.terms[curie] = (label, prefix)
        return curie, label

    def _quantity(self, obj, entity_type, entity_id, entity_name, slot, ctx, rng):
        """Flatten a value object and record its long-format measurement row.

        Keyed by (source_file, entity, slot) so an entity inlined under several
        parents contributes its number once rather than once per copy, and the
        FIRST sighting wins — matching the row merge and what the conflict
        warning promises. Writing on every sighting made the long table keep the
        last copy's number while the wide echo kept the first, so one build
        answered the same question two different ways.
        """
        if not isinstance(obj, dict):
            return {}
        mkey = (ctx["source_file"], entity_type, _s(entity_id), slot)
        unit, unit_label = self._term(
            obj.get("unit"), (ctx, entity_type, entity_id, f"{slot}.unit")
        )
        base = {
            **ctx,
            "entity_type": entity_type,
            "entity_id": _s(entity_id),
            "entity_name": entity_name,
            "slot_name": slot,
            "unit": unit,
            "unit_label": unit_label,
        }

        if rng == "QuantityRange":
            mn, mx = obj.get("min_value"), obj.get("max_value")
            if isinstance(mn, dict):
                mn = mn.get("value")
            if isinstance(mx, dict):
                mx = mx.get("value")
            flat = {
                f"{slot}_min_value": _s(mn),
                f"{slot}_max_value": _s(mx),
                f"{slot}_unit": unit,
                f"{slot}_unit_label": unit_label,
            }
            self.measurements.setdefault(mkey, {
                **base,
                "value": None, "value_num": None, "value_qualifier": None,
                "min_value": _s(mn), "max_value": _s(mx),
                "central_tendency": None, "sample_size": None,
                "variability_type": None, "variability_value": None,
                "lower_bound": None, "upper_bound": None,
            })
            return flat

        value = _s(obj.get("value"))
        var = obj.get("variability") or {}
        if not isinstance(var, dict):
            var = {}
        num, qualifier = _num(value)
        flat = {
            f"{slot}_value": value,
            f"{slot}_unit": unit,
            f"{slot}_unit_label": unit_label,
        }
        self.measurements.setdefault(mkey, {
            **base,
            "value": value, "value_num": num, "value_qualifier": qualifier,
            "min_value": None, "max_value": None,
            "central_tendency": _s(obj.get("central_tendency")),
            "sample_size": obj.get("sample_size"),
            "variability_type": _s(var.get("variability_type")),
            "variability_value": _s(var.get("value")),
            "lower_bound": _s(var.get("lower_bound")),
            "upper_bound": _s(var.get("upper_bound")),
        })
        return flat
    # -- main recursion ---------------------------------------------------
    def visit(self, obj, declared, ctx, parent=None, index=0):
        """Emit a row for `obj` and recurse into its inlined children.

        Returns the row's id so the caller can store a foreign key.
        """
        sv = self.sv
        cls = concrete_class(sv, declared, obj)
        if cls not in table_classes(sv):
            # The declared range is abstract and the object carries no type
            # designator, so there is no table to put it in. Dropping it would
            # lose the row, its subtree and its edge with no trace.
            slot = parent[2] if parent else "?"
            self.warn(
                "no-table",
                f"{ctx['source_file']}: inlined value of '{slot}' resolved to "
                f"'{cls}', which has no table (declared range '{declared}' is "
                f"abstract and no type designator was given) — subtree dropped",
            )
            return None

        if has_natural_key(sv, cls):
            row_id = obj.get("id")
            if row_id is None:
                self.warn(
                    "missing-id", f"{ctx['source_file']}: {cls} with no id, skipped"
                )
                return None
        else:
            row_id = self._surrogate_id(cls, ctx, parent, index)

        key = (ctx["source_file"], row_id)
        cls = self._unify_class(cls, key, ctx)
        row = self.rows[cls].get(key)
        first_time = row is None
        if first_time:
            row = {**ctx, "id": row_id}
            if parent:
                row["parent_type"], row["parent_id"], row["parent_slot"] = parent
            self.rows[cls][key] = row

        # Collect this sighting's values first, then merge. An entity inlined
        # under several parents is walked once per copy: a later copy may carry
        # fields an earlier stub omitted (merge those in), but if two copies
        # give the same field different values one of them is a curation error
        # and picking a winner by walk order would hide it.
        vals: dict = {}
        name = obj.get("name")
        for s in sv.class_induced_slots(cls):
            val = obj.get(s.name)
            if val is None:
                continue
            rng = s.range
            if s.designates_type:
                vals[s.name] = _s(val)
            elif is_entity(sv, rng):
                self._entity_slot(vals, s, val, rng, cls, row_id, ctx)
            elif rng in QUANTITY_CLASSES:
                vals.update(
                    self._quantity(val, cls, row_id, name, s.name, ctx, rng)
                )
            elif rng in TERM_CLASSES:
                ref = (ctx, cls, row_id, s.name)
                if s.multivalued:
                    pairs = [self._term(v, ref) for v in val or []]
                    vals[s.name] = [p[0] for p in pairs]
                    vals[f"{s.name}_labels"] = [p[1] for p in pairs]
                else:
                    curie, label = self._term(val, ref)
                    vals[s.name] = curie
                    vals[f"{s.name}_label"] = label
            else:
                if s.multivalued:
                    vals[s.name] = [_s(v) for v in (val if isinstance(val, list) else [val])]
                else:
                    vals[s.name] = val if not isinstance(val, (dict, list)) else _s(val)

        conflicts = []
        for col, value in vals.items():
            if row.get(col) is None:
                row[col] = value
            elif value is not None and row[col] != value:
                conflicts.append(f"{col}={row[col]!r} vs {value!r}")
        if conflicts:
            self.warn(
                "content-conflict",
                f"{ctx['source_file']}: two inlined copies of {cls} '{row_id}' "
                f"disagree ({'; '.join(conflicts[:3])}"
                f"{f', +{len(conflicts) - 3} more' if len(conflicts) > 3 else ''}) "
                f"— kept the first value seen",
            )
        return row_id

    def _unify_class(self, cls, key, ctx):
        """Keep one id in one table, preferring the most specific class.

        The row dedupe is per class, so an id written once as a base class and
        once as a subclass produced two rows in two tables with no warning —
        and because link targets resolve to whichever table holds the id, the
        base-class row, which is often the one carrying the real description,
        became reachable from nothing.
        """
        previous = self.id_class.get(key)
        if previous is None:
            self.id_class[key] = cls
            return cls
        if previous == cls:
            return cls
        sv = self.sv
        if previous in sv.class_ancestors(cls):
            winner, loser = cls, previous       # cls is the more specific
        elif cls in sv.class_ancestors(previous):
            winner, loser = previous, cls
        else:
            winner, loser = previous, cls       # unrelated: first one wins
        self.warn(
            "id-used-as-two-classes",
            f"{ctx['source_file']}: id '{key[1]}' is used as both {previous} "
            f"and {cls} — kept in {winner}",
        )
        if loser != winner and key in self.rows.get(loser, {}):
            # Move the already-written row into the winning table rather than
            # leaving an orphan behind in the losing one.
            stale = self.rows[loser].pop(key)
            target = self.rows[winner].setdefault(key, stale)
            if target is not stale:
                for col, value in stale.items():
                    if target.get(col) is None:
                        target[col] = value
        self.id_class[key] = winner
        return winner

    def _surrogate_id(self, cls, ctx, parent, index):
        """Stable id for a class with no identifier (EvidenceItem, PublicationReference).

        Keyed on the position the object occupies — its parent, the slot and the
        index within that slot — not on its content. A counter gave every
        sighting a fresh id, so the dedupe could never fire. Keying on content
        fixed that only for byte-identical copies, which is the wrong bar:
        every one of the conflicts these files actually contain is a near-copy
        (a truncated donor_info, a rewritten characteristic, age 52 vs 53), and
        under a content key those differ, so they would silently become extra
        rows instead of reaching the conflict warning. Position collapses them
        and routes their disagreement into that warning.
        """
        skey = (
            ctx["source_file"], cls,
            parent[0] if parent else None,
            _s(parent[1]) if parent else None,
            parent[2] if parent else None,
            index,
        )
        existing = self.surrogate_ids.get(skey)
        if existing is not None:
            return existing
        self.surrogate += 1
        row_id = f"{cls}-{self.surrogate}"
        self.surrogate_ids[skey] = row_id
        return row_id

    def _entity_slot(self, vals, s, val, rng, cls, row_id, ctx):
        """Handle a slot whose range is a class that gets its own table."""
        items = val if s.multivalued else [val]
        for index, item in enumerate(items or []):
            if isinstance(item, dict):
                child_declared = rng
                child_id = self.visit(
                    item, child_declared, ctx,
                    parent=(cls, row_id, s.name), index=index,
                )
                child_type = concrete_class(self.sv, rng, item)
                inlined = True
            else:
                child_id, child_type, inlined = item, rng, False
            if child_id is None:
                continue
            lkey = (ctx["source_file"], cls, _s(row_id), s.name, _s(child_id))
            self.links[lkey] = {
                **ctx, "parent_type": cls, "parent_id": _s(row_id),
                "parent_slot": s.name, "target_type": child_type,
                "target_id": _s(child_id), "inlined": inlined,
            }
            if not s.multivalued:
                vals[f"{s.name}_id"] = _s(child_id)

    # -- file entry point -------------------------------------------------
    def add_file(self, path: Path):
        data = yaml.safe_load(path.read_text()) or {}
        src = data.get("source_publication") or {}
        paper_id = src.get("reference") or path.name
        ctx = {"paper_id": paper_id, "source_file": path.name}
        clash = [p["source_file"] for p in self.papers if p["paper_id"] == paper_id]
        if clash:
            self.warn(
                "shared-citation",
                f"{path.name}: cites {paper_id}, already cited by "
                f"{', '.join(clash)} — both are kept, keyed by source_file",
            )
        self.papers.append({
            "paper_id": paper_id,
            "source_file": path.name,
            "reference": src.get("reference"),
            "reference_title": src.get("reference_title"),
            "doi": src.get("doi"),
        })
        for s in self.sv.class_induced_slots(ROOT_CLASS):
            val = data.get(s.name)
            if val is None or not is_entity(self.sv, s.range):
                continue
            for item in (val if s.multivalued else [val]):
                if isinstance(item, dict):
                    self.visit(
                        item, s.range, ctx,
                        # paper's key is source_file (see fix 3), not the PMID
                        parent=(PAPER_TABLE, path.name, s.name),
                    )


    def resolve_link_types(self):
        """Point every link at the class whose table actually holds the target.

        For a by-id reference the walker only knows the slot's declared range,
        and several of those ranges are abstract (Assay, AssayOutputMeasurement)
        with no table of their own. Looking the target up in the row map after
        the walk gives the concrete class, so link stays joinable.
        """
        index: dict[tuple, str] = {}
        for cls, rowmap in self.rows.items():
            for (source_file, row_id) in rowmap:
                index[(source_file, _s(row_id))] = cls
        unresolved = 0
        for link in self.links.values():
            if link["inlined"]:
                continue
            found = index.get((link["source_file"], link["target_id"]))
            if found:
                link["target_type"] = found
            else:
                unresolved += 1
        if unresolved:
            self.warn(
                "unresolved-reference",
                f"{unresolved} link row(s) reference an id that no entity in the "
                f"same file declares; target_type left as the declared range",
            )


def _s(v):
    return None if v is None else str(v)


def _num(v):
    """Parse a value into (number, qualifier).

    Values in this schema are strings so a curator can record "<0.05" or "~12".
    The qualifier is kept rather than discarded: stripping it would make
    `WHERE value_num < 0.05` silently miss the rows that meant exactly that.
    """
    if v is None:
        return None, None
    text = str(v).strip()
    qualifier = None
    for mark in ("<=", ">=", "<", ">", "~", "≈"):
        if text.startswith(mark):
            qualifier, text = mark, text[len(mark):].strip()
            break
    try:
        return float(text.replace(",", "")), qualifier
    except (TypeError, ValueError):
        return None, qualifier


# ---------------------------------------------------------------------------
# L2 views
# ---------------------------------------------------------------------------

def emit_views(sv) -> str:
    """Generate the analysis views.

    These exist so a question like "every ciliary beat frequency measured under
    PM2.5" does not require knowing that assays are split across 11 tables and
    outputs across 11 more.
    """
    assays = _subclasses(sv, "Assay")
    outputs = _subclasses(sv, "AssayOutputMeasurement")
    parts = []

    parts.append(_union_view(sv, "assay", "Assay", assays, "assay_type"))
    parts.append(
        _union_view(
            sv, "assay_output", "AssayOutputMeasurement", outputs, "output_type",
            extra=[("assay_id", '"parent_id"')],
        )
    )

    parts.append("""
-- Every number in the KB with its full experimental context: which paper,
-- which assay, which exposure, which experimental group, which key event.
-- This is the flagship table for analysis and the headline TSV export.
CREATE VIEW measurement_full AS
SELECT
    m.paper_id,
    p.reference_title,
    a.assay_type,
    a.id            AS assay_id,
    a.name          AS assay_name,
    o.output_type,
    m.entity_id     AS output_id,
    m.entity_name   AS output_name,
    o.experimental_group,
    m.slot_name     AS measurement,
    m.value,
    m.value_num,
    m.unit,
    m.unit_label,
    m.central_tendency,
    m.sample_size,
    m.variability_type,
    m.variability_value,
    m.lower_bound,
    m.upper_bound,
    e.id                                AS exposure_id,
    e.exposure_agent                    AS exposure_agent,
    e.exposure_agent_label              AS exposure_agent_label,
    e.exposure_concentration_value      AS exposure_concentration,
    e.exposure_concentration_unit_label AS exposure_concentration_unit,
    e.exposure_duration_value           AS exposure_duration,
    e.exposure_duration_unit_label      AS exposure_duration_unit,
    a.informs_on_key_event_id           AS key_event_id,
    ke.name                             AS key_event_name,
    m.source_file
FROM measurement m
LEFT JOIN assay_output o
       ON o.source_file = m.source_file AND o.id = m.entity_id
LEFT JOIN assay a
       ON a.source_file = o.source_file AND a.id = o.assay_id
LEFT JOIN "ExposureCondition" e
       ON e.source_file = o.source_file AND e.id = o.measured_under_id
LEFT JOIN "KeyEvent" ke
       ON ke.source_file = a.source_file AND ke.id = a.informs_on_key_event_id
LEFT JOIN paper p
       ON p.source_file = m.source_file;
""".strip())

    parts.append("""
-- Evidence quotes with the entity they support, resolved to one parent column.
CREATE VIEW evidence AS
SELECT
    ev.paper_id,
    ev.parent_type,
    ev.parent_id,
    ev.parent_slot,
    ev.supports,
    ev.evidence_source,
    ev.reference,
    ev.reference_title,
    ev.snippet,
    ev.explanation,
    ev.source_file
FROM "EvidenceItem" ev;
""".strip())

    parts.append("""
-- Which ontology terms the KB actually uses, and how often. Counts every
-- reference recorded in term_ref -- units, cell types, species, chemicals and
-- anatomical entities alike -- so a term with no uses really is unused.
CREATE VIEW term_usage AS
SELECT
    t.id,
    t.label,
    t.prefix,
    COALESCE(u.n_uses, 0)   AS n_uses,
    COALESCE(u.n_papers, 0) AS n_papers,
    u.slots
FROM term t
LEFT JOIN (
    SELECT
        term_id                            AS id,
        COUNT(*)                           AS n_uses,
        COUNT(DISTINCT source_file)         AS n_papers,
        STRING_AGG(DISTINCT slot_name, ', ') AS slots
    FROM term_ref
    GROUP BY term_id
) u ON u.id = t.id;
""".strip())

    return "\n\n".join(parts) + "\n"


def _subclasses(sv, parent: str) -> list[str]:
    """Concrete descendants of an abstract parent class, in schema order."""
    return [
        c for c in sorted(table_classes(sv))
        if parent in sv.class_ancestors(c) and c != parent
    ]


def _union_view(sv, view, parent, classes, type_col, extra=None):
    """UNION ALL the subclass tables over the columns they all inherit."""
    base = [n for n, _ in columns_for(sv, parent)]
    cols = ["paper_id", "source_file", "parent_id"] + base
    selects = []
    for cls in classes:
        available = {n for n, _ in columns_for(sv, cls)} | {
            "paper_id", "source_file", "parent_id", "parent_type", "parent_slot"
        }
        exprs = [f"'{cls}' AS {type_col}"]
        for c in cols:
            exprs.append(f'"{c}"' if c in available else f'NULL AS "{c}"')
        for alias, expr in (extra or []):
            exprs.append(f'{expr} AS "{alias}"')
        selects.append(f'SELECT {", ".join(exprs)} FROM "{cls}"')
    body = "\nUNION ALL\n".join(selects)
    return f"-- {view}: all {len(classes)} {parent} subclasses in one relation.\nCREATE VIEW {view} AS\n{body};"


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

def _execute_script(con, script: str):
    """Run a multi-statement script, skipping -- comment lines.

    The comment lines matter: LinkML-style DDL comments contain semicolons and
    prose, so they must be stripped before splitting rather than after.
    """
    clean = "\n".join(
        l for l in script.splitlines() if not l.lstrip().startswith("--")
    )
    for stmt in (s.strip() for s in clean.split(";")):
        if stmt:
            con.execute(stmt)


def _insert(con, table, rows):
    if not rows:
        return 0
    cols = [r[0] for r in con.execute(f'DESCRIBE "{table}"').fetchall()]
    # A row key with no matching column would otherwise be shed in silence,
    # which is how schema drift turns into quietly missing data.
    extra = {k for r in rows for k in r} - set(cols)
    if extra:
        raise SystemExit(
            f'{table}: row keys with no column: {sorted(extra)}. '
            f"The schema mapping and the DDL have drifted apart."
        )
    placeholders = ", ".join("?" for _ in cols)
    payload = [tuple(r.get(c) for c in cols) for r in rows]
    con.executemany(
        f'INSERT INTO "{table}" ({", ".join(chr(34)+c+chr(34) for c in cols)}) '
        f"VALUES ({placeholders})",
        payload,
    )
    return len(payload)


def build(kb_dir: Path, out: Path, schema_path: str) -> dict:
    import duckdb

    sv = load_schema(schema_path)
    files = sorted(kb_dir.glob("*.yaml"))
    if not files:
        raise SystemExit(f"No YAML files in {kb_dir} — nothing to build.")

    b = Builder(sv)
    for f in files:
        b.add_file(f)
    b.resolve_link_types()

    out.parent.mkdir(parents=True, exist_ok=True)
    out.unlink(missing_ok=True)
    con = duckdb.connect(str(out))
    _execute_script(con, emit_ddl(sv))

    counts = {}
    counts["paper"] = _insert(con, "paper", b.papers)
    for cls, rowmap in b.rows.items():
        n = _insert(con, cls, list(rowmap.values()))
        if n:
            counts[cls] = n
    counts["measurement"] = _insert(con, "measurement", list(b.measurements.values()))
    counts["link"] = _insert(con, "link", list(b.links.values()))
    counts["term"] = _insert(
        con, "term",
        [{"id": k, "label": v[0], "prefix": v[1]} for k, v in sorted(b.terms.items())],
    )
    counts["term_ref"] = _insert(
        con, "term_ref",
        [
            {
                "paper_id": p_, "source_file": sf, "entity_type": et,
                "entity_id": eid, "slot_name": slot, "term_id": tid,
            }
            for (p_, sf, et, eid, slot, tid) in sorted(b.term_refs)
        ],
    )
    _execute_script(con, emit_views(sv))
    con.close()
    return {"files": len(files), "counts": counts, "warnings": b.warnings}


# ---------------------------------------------------------------------------
# TSV export
# ---------------------------------------------------------------------------

def dump_tsv(db: Path, out_dir: Path) -> list[str]:
    """One .tsv per table and view.

    DuckDB's own `EXPORT DATABASE` is one command but lowercases filenames and
    writes tab-delimited data into files named `.csv`, which Excel mis-parses on
    double-click. Copying table by table keeps the class names and an honest
    extension. LIST columns are joined with '; ' so the output stays rectangular.
    """
    import duckdb

    con = duckdb.connect(str(db), read_only=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    rels = con.execute(
        "SELECT table_name, table_type FROM information_schema.tables "
        "WHERE table_schema = 'main' ORDER BY table_type, table_name"
    ).fetchall()
    for name, _type in rels:
        cols = con.execute(f'DESCRIBE "{name}"').fetchall()
        exprs = []
        for col, typ, *_ in cols:
            if typ.endswith("[]"):
                exprs.append(f'array_to_string("{col}", \'; \') AS "{col}"')
            else:
                exprs.append(f'"{col}"')
        target = out_dir / f"{name}.tsv"
        con.execute(
            f'COPY (SELECT {", ".join(exprs)} FROM "{name}") '
            f"TO '{target}' (FORMAT CSV, DELIMITER '\t', HEADER, QUOTE '\"')"
        )
        written.append(target.name)
    con.close()
    return written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def resolve_kb_dir(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit)
    if DEFAULT_KB_DIR.exists() and any(DEFAULT_KB_DIR.glob("*.yaml")):
        return DEFAULT_KB_DIR
    print(
        f"note: {DEFAULT_KB_DIR.relative_to(ROOT)} is empty, "
        f"building from {FALLBACK_KB_DIR.relative_to(ROOT)} instead",
        file=sys.stderr,
    )
    return FALLBACK_KB_DIR


def default_schema() -> str:
    from importlib.resources import files as pkg_files

    return str(pkg_files("soma") / "schema" / "soma.yaml")


EXAMPLES_PER_CATEGORY = 3


def _report_warnings(warnings, out=None):
    """Print warnings grouped by category, a few examples from each.

    Grouped rather than truncated as one flat list: a build with thirty content
    conflicts would otherwise push the single "two files cite the same paper"
    line off the end, and that is the one that changes what a curator does. Every
    category is always named with its full count, so nothing hides.
    """
    out = out or sys.stderr
    if not warnings:
        return
    groups: dict[str, dict[str, int]] = {}
    for category, message in warnings:
        groups.setdefault(category, {})
        groups[category][message] = groups[category].get(message, 0) + 1
    print(f"\n{len(warnings)} warning(s) in {len(groups)} category(ies):", file=out)
    for category in sorted(groups, key=lambda c: -sum(groups[c].values())):
        messages = groups[category]
        total = sum(messages.values())
        print(f"\n  [{category}] {total} warning(s), {len(messages)} distinct:", file=out)
        for message, n in list(messages.items())[:EXAMPLES_PER_CATEGORY]:
            print(f"    {message}{f'  (x{n})' if n > 1 else ''}", file=out)
        if len(messages) > EXAMPLES_PER_CATEGORY:
            print(
                f"    ... and {len(messages) - EXAMPLES_PER_CATEGORY} more distinct "
                f"[{category}] warning(s)",
                file=out,
            )


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--kb-dir")
    ap.add_argument("--output", default=str(DEFAULT_OUT))
    ap.add_argument("--schema", default=None)
    ap.add_argument("--tsv-dir", help="also dump every table/view as TSV here")
    ap.add_argument("--ddl-only", action="store_true", help="print DDL + views, build nothing")
    args = ap.parse_args(argv)

    schema_path = args.schema or default_schema()
    if args.ddl_only:
        sv = load_schema(schema_path)
        print(emit_ddl(sv))
        print(emit_views(sv))
        return 0

    kb_dir = resolve_kb_dir(args.kb_dir)
    out = Path(args.output)
    result = build(kb_dir, out, schema_path)

    print(f"Built {out} from {result['files']} files in {kb_dir}")
    nonempty = {k: v for k, v in sorted(result["counts"].items()) if v}
    print(f"{len(nonempty)} non-empty tables, {sum(nonempty.values())} rows")
    for k, v in sorted(nonempty.items(), key=lambda kv: -kv[1])[:12]:
        print(f"    {k:34} {v:6}")
    _report_warnings(result["warnings"])

    if args.tsv_dir:
        written = dump_tsv(out, Path(args.tsv_dir))
        print(f"Wrote {len(written)} TSV files to {args.tsv_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
